language: python
python:
  - 3.8
  - 3.7
  - 3.6

script:
  - pytest

before_install:
  - "echo before install"
  - "sudo apt-get install gcc gfortran"
  - "pip install -U pip"

install:
  - "pip install -r requirements/default.txt"
  - "pip install -r requirements/extra.txt"
  - "pip install -r requirements/test.txt"
  - "pip install -U tox-travis"
  - "python setup.py install"

script:
  - "tox"
